# config for RNA-Variant discovery snakemake pipeline #

RAW_DATA:
    "../../data/raw_data/PRJNA386593"

DATA: 
  "../../data/PRJNA386593"

LIB_PARAMS:
  "config/lib_params_GSE99249.tsv"

GENOME:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa"
CHROM_SIZES:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa.fai"
GENOME_DIR:
    "/beevol/home/rbilab/ref/indices/star/human/GRCh38-UCSC-2.7.9a"

FASTQ_SUFFIX:
    R1: "1.fastq.gz"
    R2: "2.fastq.gz"

REDITOOLS_PARAMS: 
    " -s 1 -q 10 -bq 20 -mbp 7 -l 20 -men 1 -T 1 -C -H "
EDIT_SITES:
    ""
REDITOOLS:
    "/beevol/home/riemondy/src/REDItools2/src/cineca/reditools.py"

ACCESSORY_SRC:
    "/beevol/home/riemondy/Projects/vicens/src/REDItools/accessory"

SALMON_IDX:
      "/beevol/home/rbilab/ref/indices/alevin/hg38/hg38_idx"

TRANSCRIPTS:
    "/beevol/home/rbilab/ref/indices/alevin/hg38/gencode.v35.transcripts.fa.gz"

FASTP: "/beevol/home/riemondy/bin/fastp/fastp"
CUTADAPT: "cutadapt"

ANNOT_PARAMS:
    SNP: " -c 1,2,3 -u -a /beevol/home/riemondy/Projects/vicens/dbases/rediportal/dbsnp151.gff.gz -n snp " 
    REPEATS: " -c 1,2,3 -u -a /beevol/home/riemondy/Projects/vicens/dbases/rediportal/rmsk.sorted.gff.gz -n repeats "
    TX: "-c 1,2 -a /beevol/home/riemondy/Projects/vicens/dbases/rediportal/gencode.v37.annotation.gtf.bg.gz -n gene "

CMD_PARAMS:
    cutadapt: " -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 30 "
    fastp: " -u 10 -l 50 -y -x -q 25 "
    salmon_quant: " --validateMappings --libType 'A' --numBootstraps 50 "
    salmon_idx: " -k 31 --gencode "
