# config for RNA-Variant discovery snakemake pipeline #

RAW_DATA:
    "/beevol/home/riemondy/Projects/vicens/data/2022-12-01/raw_data"

DATA: 
    "/beevol/home/riemondy/Projects/vicens/data/2022-12-01"

LIB_PARAMS:
  "config/lib_params_221201.tsv"

GENOME:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa"
CHROM_SIZES:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa.fai"
GENOME_DIR:
    "/beevol/home/rbilab/ref/indices/star/human/GRCh38-UCSC-2.7.9a"

FASTQ_SUFFIX:
    R1: "R1_001.fastq.gz"
    R2: "R2_001.fastq.gz"

REDITOOLS_PARAMS:
    #" -s 1 -q 10 -bq 20 -mbp 7 -l 20 -men 1 -T 1 -C -H "
    " -s 2 -c1 -m255 -v1 -q20 -e -n0.0 -u -p  -g 2 -S -H "
EDIT_SITES:
    "/beevol/home/riemondy/Projects/vicens/dbases/rediportal/rediportal_hg38.sorted.gtf.gz"

REDITOOLS:
    "/beevol/home/riemondy/Projects/vicens/src/REDItools/main/"

ACCESSORY_SRC:
    "/beevol/home/riemondy/Projects/vicens/src/REDItools/accessory"

SALMON_IDX:
    "../../dbases/indices/salmon/gencode.v35.transgenes/salmon_idx"

TRANSCRIPTS:
    "../../dbases/seqs/transcripts/gencode.v35.transcripts.transgene.fasta"

FASTP: "/beevol/home/riemondy/bin/fastp/fastp"
CUTADAPT: "cutadapt"

ANNOT_PARAMS:
    SNP: " -c 1,2,3 -u -a /beevol/home/riemondy/Projects/vicens/dbases/rediportal/dbsnp151.gff.gz -n snp " 
    REPEATS: " -c 1,2,3 -u -a /beevol/home/riemondy/Projects/vicens/dbases/rediportal/rmsk.sorted.gff.gz -n repeats "
    TX: "-c 1,2 -a /beevol/home/riemondy/Projects/vicens/dbases/rediportal/gencode.v37.annotation.gtf.bg.gz -n gene "

CMD_PARAMS:
    cutadapt: " -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 30 "
    fastp: " -u 10 -l 50 -y -x -q 25 "
    salmon_quant: " --validateMappings --libType 'A' --numBootstraps 50 "
    salmon_idx: " -k 31 --gencode "
