# config for RNA-Variant discovery snakemake pipeline #

#PICARD:
#  "~/src/picard/picard.jar"
#
#GATK:
#  "/cluster/software/modules-sw/GATK/3.8/GenomeAnalysisTK.jar"
#
#SNPEFF:
#  "/beevol/home/riemondy/bin/snpEff"
#
#PANDOC:
#  "/beevol/home/riemondy/bin/pandoc/"

LIB:
  "./workflow/scripts/"

RAW_DATA:
  "/beevol/home/riemondy/Projects/vicens/data/star"

DATA: 
  "/beevol/home/riemondy/Projects/vicens/data/hyperediting/GSE99304"

GENOME:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa"

SIMPLE_REPEATS:
  "/beevol/home/riemondy/Projects/vicens/dbases/hyperediting/unique_simple_repeats.txt"

# on of fr-first-strand or fr-second-strand
LIBRARY_TYPE:
    - "fr-second-strand"

FASTQ:
    - SRR5605163/SRR5605163
    - SRR5605164/SRR5605164
    - SRR5605165/SRR5605165
    - SRR5605166/SRR5605166
    - SRR5605167/SRR5605167
    - SRR5605168/SRR5605168

FASTQ_SUFFIX:
    R1: "_Unmapped.out.mate1.fastq.gz"
    R2: "_Unmapped.out.mate2.fastq.gz"

BAM_SUFFIX:
    "_sorted.bam"

pos_ref:
  - A
  - A
  - A  
  - G
  - G
  - G
  - C
  - C
  - C
  - T
  - T
  - T  

pos_alt: 
  - G 
  - C 
  - T
  - A
  - C
  - T
  - A
  - G 
  - T
  - A
  - G
  - C
