# config for RNA-Variant discovery snakemake pipeline #

#PICARD:
#  "~/src/picard/picard.jar"
#
#GATK:
#  "/cluster/software/modules-sw/GATK/3.8/GenomeAnalysisTK.jar"
#
#SNPEFF:
#  "/beevol/home/riemondy/bin/snpEff"
#
#PANDOC:
#  "/beevol/home/riemondy/bin/pandoc/"

LIB:
  "./workflow/scripts/"

RAW_DATA:
  "/beevol/home/riemondy/Projects/vicens/data/star"

DATA: 
  "/beevol/home/riemondy/Projects/vicens/data/hyperediting/GSE99249"

GENOME:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa"

SIMPLE_REPEATS:
  "/beevol/home/riemondy/Projects/vicens/dbases/hyperediting/unique_simple_repeats.txt"

# on of fr-first-strand or fr-second-strand
LIBRARY_TYPE:
    - "fr-first-strand"

FASTQ:
    - SRR5564260/SRR5564260
    - SRR5564261/SRR5564261
    - SRR5564262/SRR5564262
    - SRR5564263/SRR5564263
    - SRR5564264/SRR5564264
    - SRR5564265/SRR5564265
    - SRR5564266/SRR5564266
    - SRR5564267/SRR5564267
    - SRR5564268/SRR5564268
    - SRR5564269/SRR5564269
    - SRR5564270/SRR5564270
    - SRR5564271/SRR5564271
    - SRR5564272/SRR5564272
    - SRR5564273/SRR5564273
    - SRR5564274/SRR5564274
    - SRR5564275/SRR5564275
    - SRR5564276/SRR5564276
    - SRR5564277/SRR5564277

FASTQ_SUFFIX:
    R1: "_Unmapped.out.mate1.fastq.gz"
    R2: "_Unmapped.out.mate2.fastq.gz"

BAM_SUFFIX:
    "_sorted.bam"

pos_ref:
  - A
  - A
  - A  
  - G
  - G
  - G
  - C
  - C
  - C
  - T
  - T
  - T  

pos_alt: 
  - G 
  - C 
  - T
  - A
  - C
  - T
  - A
  - G 
  - T
  - A
  - G
  - C
