# config for RNA-Variant discovery snakemake pipeline #
#path to scripts directory
LIB:
  "/home/Mary/RNA_Seq_Analysis/KENT_Code/pipeline/hyperediting/workflow/scripts/"
#path to raw FASTQ files
RAW_DATA:
    "/data7/Chung_H_et_al/2024-04-04/star/"
#directory where output files will be stored
DATA:
    "/data7/Chung_H_et_al/2024-04-04/hyperediting"
#path to indexed reference genome
GENOME:
  "/data7/genome_Hg38/GRCh38.primary_assembly.genome.fa"

# path to 3-base bwa indices, will be generated if they do not exist
BWA_IDX:
  "/home/Mary/RNA_Seq_Analysis/KENT_Code/pipeline/hyperediting_Chung/bwa_idx"
#path to simple repeat file in /hyperediting/dbases directory, can be commented
SIMPLE_REPEATS:
  "/data7/KENT_code/dbases/hyperediting/unique_simple_repeats.txt"

# strand-specific information of sequenced data; fr-first-strand or fr-second-strand
LIBRARY_TYPE:
    - "fr-first-strand"
# condition/group name prefix (conditions are in triplicates)
FASTQ:
  - ADAR1_KO_1/ADAR1_KO_1
  - ADAR1_KO_2/ADAR1_KO_2
  - ADAR1_KO_3/ADAR1_KO_3
  - ADAR1_KO_Interferon_1/ADAR1_KO_Interferon_1
  - ADAR1_KO_Interferon_2/ADAR1_KO_Interferon_2
  - ADAR1_KO_Interferon_3/ADAR1_KO_Interferon_3
  - ADAR1p150_KO_1/ADAR1p150_KO_1
  - ADAR1p150_KO_2/ADAR1p150_KO_2
  - ADAR1p150_KO_3/ADAR1p150_KO_3
  - ADAR1p150_KO_Interferon_1/ADAR1p150_KO_Interferon_1
  - ADAR1p150_KO_Interferon_2/ADAR1p150_KO_Interferon_2
  - ADAR1p150_KO_Interferon_3/ADAR1p150_KO_Interferon_3
  - wildtype_1/wildtype_1
  - wildtype_2/wildtype_2
  - wildtype_3/wildtype_3
  - wildtype_Interferon_1/wildtype_Interferon_1
  - wildtype_Interferon_2/wildtype_Interferon_2
  - wildtype_Interferon_3/wildtype_Interferon_3

# BAM filename suffixes generated after editing preprocessing; found in 'DATA' directory
FASTQ_SUFFIX:
    R1: "_Unmapped.out.mate1.fastq.gz"
    R2: "_Unmapped.out.mate2.fastq.gz"

BAM_SUFFIX:
    "_dedup_sorted.bam"

pos_ref:
  - A
  - A
  - A
  - G
  - G
  - G
  - C
  - C
  - C
  - T
  - T
  - T

pos_alt:
  - G
  - C
  - T
  - A
  - C
  - T
  - A
  - G
  - T
  - A
  - G
  - C

