# config for RNA-Variant discovery snakemake pipeline #
#path to scripts directory
LIB:
  "./workflow/scripts/"
#path to raw FASTQ files
RAW_DATA:
    "/beevol/home/riemondy/Projects/vicens/data/2024-04-04/star"
#directory where output files will be stored
DATA: 
    "/beevol/home/riemondy/Projects/vicens/data/2024-04-04/hyperediting"
#path to indexed reference genome 
GENOME:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa"

 # path to 3-base bwa indices, will be generated if they do not exist
BWA_IDX:
  "/beevol/home/riemondy/Projects/vicens/dbases/hyperediting/bwa_idx"
#path to simple repeat file in /hyperediting/dbases directory, can be commented
SIMPLE_REPEATS:
  "/beevol/home/riemondy/Projects/vicens/dbases/hyperediting/unique_simple_repeats.txt"

# strand-specific information of sequenced data; fr-first-strand or fr-second-strand
LIBRARY_TYPE:
    - "fr-first-strand"
# condition/group name
FASTQ:
  - ADAR1_KO_A/ADAR1_KO_A
  - ADAR1_KO_B/ADAR1_KO_B
  - ADAR1_KO_C/ADAR1_KO_C
  - ADAR1_KO_H910Q_E912A_A/ADAR1_KO_H910Q_E912A_A
  - ADAR1_KO_H910Q_E912A_B/ADAR1_KO_H910Q_E912A_B
  - ADAR1_KO_H910Q_E912A_C/ADAR1_KO_H910Q_E912A_C
  - ADAR1_KO_p150_minus_DOX_A/ADAR1_KO_p150_minus_DOX_A
  - ADAR1_KO_p150_minus_DOX_B/ADAR1_KO_p150_minus_DOX_B
  - ADAR1_KO_p150_minus_DOX_C/ADAR1_KO_p150_minus_DOX_C
  - ADAR1_KO_p150_plus_DOX_A/ADAR1_KO_p150_plus_DOX_A
  - ADAR1_KO_p150_plus_DOX_B/ADAR1_KO_p150_plus_DOX_B
  - ADAR1_KO_p150_plus_DOX_C/ADAR1_KO_p150_plus_DOX_C
  - ADAR1p150_KO_A/ADAR1p150_KO_A
  - ADAR1p150_KO_B/ADAR1p150_KO_B
  - ADAR1p150_KO_C/ADAR1p150_KO_C
  - H910Q_E912A_A/H910Q_E912A_A
  - H910Q_E912A_B/H910Q_E912A_B
  - H910Q_E912A_C/H910Q_E912A_C
  - N173A_Y177A_A/N173A_Y177A_A
  - N173A_Y177A_B/N173A_Y177A_B
  - N173A_Y177A_C/N173A_Y177A_C
  - N173S_A/N173S_A
  - N173S_B/N173S_B
  - N173S_C/N173S_C
  - P193A_A/P193A_A
  - P193A_B/P193A_B
  - P193A_C/P193A_C
  - deltaZalpha_A/deltaZalpha_A
  - deltaZalpha_B/deltaZalpha_B
  - deltaZalpha_C/deltaZalpha_C
  - deltaZbeta_A/deltaZbeta_A
  - deltaZbeta_B/deltaZbeta_B
  - deltaZbeta_C/deltaZbeta_C
  - delta_one_A/delta_one_A
  - delta_one_B/delta_one_B
  - delta_one_C/delta_one_C
  - double_A/double_A
  - double_B/double_B
  - double_C/double_C
  - p150_minus_DOX_A/p150_minus_DOX_A
  - p150_minus_DOX_B/p150_minus_DOX_B
  - p150_minus_DOX_C/p150_minus_DOX_C
  - p150_plus_DOX_1mg_A/p150_plus_DOX_1mg_A
  - p150_plus_DOX_1mg_B/p150_plus_DOX_1mg_B
  - p150_plus_DOX_1mg_C/p150_plus_DOX_1mg_C
  - p150_plus_DOX_A/p150_plus_DOX_A
  - p150_plus_DOX_B/p150_plus_DOX_B
  - p150_plus_DOX_C/p150_plus_DOX_C
  - wild-type_minus_IFNb_A/wild-type_minus_IFNb_A
  - wild-type_minus_IFNb_B/wild-type_minus_IFNb_B
  - wild-type_minus_IFNb_C/wild-type_minus_IFNb_C
  - wild-type_plus_IFNb_A/wild-type_plus_IFNb_A
  - wild-type_plus_IFNb_B/wild-type_plus_IFNb_B
  - wild-type_plus_IFNb_C/wild-type_plus_IFNb_C
  - wild-type_plus_IFNb_plus_DOX_A/wild-type_plus_IFNb_plus_DOX_A
  - wild-type_plus_IFNb_plus_DOX_B/wild-type_plus_IFNb_plus_DOX_B
  - wild-type_plus_IFNb_plus_DOX_C/wild-type_plus_IFNb_plus_DOX_C

# BAM filename suffixes generated after editing preprocessing
FASTQ_SUFFIX:
    R1: "_Unmapped.out.mate1.fastq.gz"
    R2: "_Unmapped.out.mate2.fastq.gz"

BAM_SUFFIX:
    "_dedup_sorted.bam"

pos_ref:
  - A
  - A
  - A  
  - G
  - G
  - G
  - C
  - C
  - C
  - T
  - T
  - T  

pos_alt: 
  - G 
  - C 
  - T
  - A
  - C
  - T
  - A
  - G 
  - T
  - A
  - G
  - C
