# config for RNA-Variant discovery snakemake pipeline #

#PICARD:
#  "~/src/picard/picard.jar"
#
#GATK:
#  "/cluster/software/modules-sw/GATK/3.8/GenomeAnalysisTK.jar"
#
#SNPEFF:
#  "/beevol/home/riemondy/bin/snpEff"
#
#PANDOC:
#  "/beevol/home/riemondy/bin/pandoc/"

LIB:
  "./workflow/scripts/"

RAW_DATA:
  "/beevol/home/riemondy/dev/hyperscan/tests/files"

DATA: 
  "/beevol/home/riemondy/dev/hyperscan/tests/files/porath_output"

GENOME:
  "/beevol/home/rbilab/ref/genome/human/GRCh38/dna/Homo_sapiens.GRCh38.dna.primary_assembly.UCSC.fa"

BWA_IDX:
      "/beevol/home/riemondy/Projects/vicens/dbases/hyperediting/bwa_idx"

SIMPLE_REPEATS:
  "/beevol/home/riemondy/Projects/vicens/dbases/hyperediting/unique_simple_repeats.txt"

# on of fr-first-strand or fr-second-strand
LIBRARY_TYPE:
    - "fr-first-strand"

FASTQ:
    - SRR5564269
    - SRR5564277

FASTQ_SUFFIX:
    R1: "_Unmapped.out.mate1.fastq.gz"
    R2: "_Unmapped.out.mate2.fastq.gz"

BAM_SUFFIX:
    "_dedup_sorted.bam"

pos_ref:
  - A
  - A
  - A  
  - G
  - G
  - G
  - C
  - C
  - C
  - T
  - T
  - T  

pos_alt: 
  - G 
  - C 
  - T
  - A
  - C
  - T
  - A
  - G 
  - T
  - A
  - G
  - C
